-- Add more popular e-commerce sites
INSERT INTO public.bot_sites (name, base_url, site_type, selectors, rate_limit_ms, status) VALUES
('Zara', 'https://www.zara.com', 'fashion', '{"title": ".product-detail-info__header-name", "price": ".price__amount", "stock": ".product-detail-actions__action-button"}', 2000, 'active'),
('H&M', 'https://www2.hm.com', 'fashion', '{"title": ".ProductName-module--productName__3J-0B", "price": ".Price-module--main__3HXg3", "stock": ".Button-module--button__1YcJo"}', 1500, 'active'),
('Uniqlo', 'https://www.uniqlo.com', 'fashion', '{"title": ".pdp-product-name", "price": ".pdp-product-price", "stock": ".fr-product-form-add-to-cart"}', 1500, 'active'),
('Lululemon', 'https://shop.lululemon.com', 'fashion', '{"title": ".pdp-product-name", "price": ".product-price", "stock": ".add-to-cart-button"}', 2000, 'active'),
('Patagonia', 'https://www.patagonia.com', 'fashion', '{"title": ".pdp-product-name", "price": ".price", "stock": ".add-to-cart"}', 1500, 'active'),
('Under Armour', 'https://www.underarmour.com', 'fashion', '{"title": ".product-title", "price": ".price-current", "stock": ".add-to-cart"}', 1500, 'active'),
('New Balance', 'https://www.newbalance.com', 'sneaker', '{"title": ".pdp-product-name", "price": ".price-now", "stock": ".add-to-cart-button"}', 1500, 'active'),
('Converse', 'https://www.converse.com', 'sneaker', '{"title": ".pdp-product-name", "price": ".notranslate", "stock": ".add-to-cart-button"}', 1500, 'active'),
('Vans', 'https://www.vans.com', 'sneaker', '{"title": ".product-title", "price": ".product-price", "stock": ".product-form__cart-submit"}', 1500, 'active'),
('Puma', 'https://us.puma.com', 'sneaker', '{"title": ".product-intro__title", "price": ".price", "stock": ".add-to-cart"}', 1500, 'active'),
('Urban Outfitters', 'https://www.urbanoutfitters.com', 'fashion', '{"title": ".product-title", "price": ".c-pwa-product-price__current", "stock": ".c-pwa-add-to-bag"}', 2000, 'active'),
('Anthropologie', 'https://www.anthropologie.com', 'fashion', '{"title": ".product-name", "price": ".product-sale-price", "stock": ".add-to-bag-button"}', 2000, 'active'),
('REI', 'https://www.rei.com', 'retail', '{"title": ".product-title", "price": ".price-current", "stock": ".add-to-cart-button"}', 1500, 'active'),
('Dick''s Sporting Goods', 'https://www.dickssportinggoods.com', 'retail', '{"title": ".product-title", "price": ".price-current", "stock": ".add-to-cart"}', 1500, 'active'),
('Academy Sports', 'https://www.academy.com', 'retail', '{"title": ".product-title", "price": ".price", "stock": ".add-to-cart-button"}', 1500, 'active'),
('Macy''s', 'https://www.macys.com', 'retail', '{"title": ".product-title", "price": ".price", "stock": ".add-to-bag-button"}', 1500, 'active'),
('Nordstrom', 'https://www.nordstrom.com', 'fashion', '{"title": ".product-title", "price": ".price", "stock": ".add-to-bag"}', 2000, 'active'),
('Saks Fifth Avenue', 'https://www.saksfifthavenue.com', 'fashion', '{"title": ".product-title", "price": ".price", "stock": ".add-to-bag"}', 2000, 'active'),
('Neiman Marcus', 'https://www.neimanmarcus.com', 'fashion', '{"title": ".product-name", "price": ".price", "stock": ".add-to-shopping-bag"}', 2000, 'active'),
('Sephora', 'https://www.sephora.com', 'beauty', '{"title": ".product-name", "price": ".price", "stock": ".add-to-basket"}', 2000, 'active'),
('Ulta Beauty', 'https://www.ulta.com', 'beauty', '{"title": ".product-title", "price": ".price", "stock": ".add-to-bag"}', 2000, 'active'),
('GameStop', 'https://www.gamestop.com', 'gaming', '{"title": ".product-name", "price": ".price", "stock": ".add-to-cart"}', 1500, 'active'),
('Best Buy', 'https://www.bestbuy.com', 'electronics', '{"title": ".product-title", "price": ".current-price", "stock": ".fulfillment-add-to-cart-button"}', 1500, 'active'),
('B&H Photo', 'https://www.bhphotovideo.com', 'electronics', '{"title": ".product-title", "price": ".price", "stock": ".add-to-cart-button"}', 1500, 'active'),
('Micro Center', 'https://www.microcenter.com', 'electronics', '{"title": ".product-title", "price": ".price", "stock": ".add-to-cart"}', 1500, 'active');