// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akdiemmxgvffopxmudia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZGllbW14Z3ZmZm9weG11ZGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzU2NDMsImV4cCI6MjA2OTI1MTY0M30.4HBC10Sc-ZLO2R-yJqOtvDLGroLPkZ7Pllered9-wAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});